"""First migration

Revision ID: fdeb3e8ca3c7
Revises: 
Create Date: 2018-02-17 09:58:32.225803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeb3e8ca3c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacktype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npcname', sa.String(length=64), nullable=False),
    sa.Column('displayname', sa.String(length=64), nullable=True),
    sa.Column('imageurl', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', 'npcname')
    )
    op.create_index(op.f('ix_npc_displayname'), 'npc', ['displayname'], unique=False)
    op.create_index(op.f('ix_npc_npcname'), 'npc', ['npcname'], unique=True)
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spellname', sa.String(length=64), nullable=False),
    sa.Column('spelllevel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'spellname')
    )
    op.create_index(op.f('ix_spell_spelllevel'), 'spell', ['spelllevel'], unique=False)
    op.create_index(op.f('ix_spell_spellname'), 'spell', ['spellname'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weaponname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'weaponname')
    )
    op.create_index(op.f('ix_weapon_weaponname'), 'weapon', ['weaponname'], unique=True)
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaignname', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_campaignname'), 'campaign', ['campaignname'], unique=True)
    op.create_table('spellattack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attacktype.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weaponattack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attacktype.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playercharacter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charactername', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playercharacter_charactername'), 'playercharacter', ['charactername'], unique=True)
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('playercharacter_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['playercharacter_id'], ['playercharacter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_session'), 'stat', ['session'], unique=False)
    op.create_index(op.f('ix_stat_timestamp'), 'stat', ['timestamp'], unique=False)
    op.create_table('hit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('attacktype_id', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attacktype_id'], ['attacktype.id'], ),
    sa.ForeignKeyConstraint(['id'], ['stat.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hit_damage'), 'hit', ['damage'], unique=False)
    op.create_table('miss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('attacktype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attacktype_id'], ['attacktype.id'], ),
    sa.ForeignKeyConstraint(['id'], ['stat.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npckilled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stat.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spellused',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stat.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spellused')
    op.drop_table('npckilled')
    op.drop_table('miss')
    op.drop_index(op.f('ix_hit_damage'), table_name='hit')
    op.drop_table('hit')
    op.drop_index(op.f('ix_stat_timestamp'), table_name='stat')
    op.drop_index(op.f('ix_stat_session'), table_name='stat')
    op.drop_table('stat')
    op.drop_index(op.f('ix_playercharacter_charactername'), table_name='playercharacter')
    op.drop_table('playercharacter')
    op.drop_table('weaponattack')
    op.drop_table('spellattack')
    op.drop_index(op.f('ix_campaign_campaignname'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_weapon_weaponname'), table_name='weapon')
    op.drop_table('weapon')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_spell_spellname'), table_name='spell')
    op.drop_index(op.f('ix_spell_spelllevel'), table_name='spell')
    op.drop_table('spell')
    op.drop_index(op.f('ix_npc_npcname'), table_name='npc')
    op.drop_index(op.f('ix_npc_displayname'), table_name='npc')
    op.drop_table('npc')
    op.drop_table('attacktype')
    # ### end Alembic commands ###
